export const CURRENCIES = [
  { code: "USD", symbol: "$", name: "US Dollar", country: "United States", decimals: 2 },
  { code: "EUR", symbol: "\u20AC", name: "Euro", country: "Europe", decimals: 2 },
  { code: "GBP", symbol: "\u00A3", name: "British Pound", country: "United Kingdom", decimals: 2 },
  { code: "JPY", symbol: "\u00A5", name: "Japanese Yen", country: "Japan", decimals: 0 },
  { code: "CNY", symbol: "\u00A5", name: "Chinese Yuan", country: "China", decimals: 2 },
  { code: "CHF", symbol: "CHF", name: "Swiss Franc", country: "Switzerland", decimals: 2 },
  { code: "CAD", symbol: "C$", name: "Canadian Dollar", country: "Canada", decimals: 2 },
  { code: "AUD", symbol: "A$", name: "Australian Dollar", country: "Australia", decimals: 2 },
  { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar", country: "New Zealand", decimals: 2 },
  { code: "INR", symbol: "\u20B9", name: "Indian Rupee", country: "India", decimals: 2 },
  { code: "KRW", symbol: "\u20A9", name: "South Korean Won", country: "South Korea", decimals: 0 },
  { code: "BRL", symbol: "R$", name: "Brazilian Real", country: "Brazil", decimals: 2 },
  { code: "MXN", symbol: "MX$", name: "Mexican Peso", country: "Mexico", decimals: 2 },
  { code: "ZAR", symbol: "R", name: "South African Rand", country: "South Africa", decimals: 2 },
  { code: "RUB", symbol: "\u20BD", name: "Russian Ruble", country: "Russia", decimals: 2 },
  { code: "TRY", symbol: "\u20BA", name: "Turkish Lira", country: "Turkey", decimals: 2 },
  { code: "PLN", symbol: "z\u0142", name: "Polish Zloty", country: "Poland", decimals: 2 },
  { code: "SEK", symbol: "kr", name: "Swedish Krona", country: "Sweden", decimals: 2 },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone", country: "Norway", decimals: 2 },
  { code: "DKK", symbol: "kr", name: "Danish Krone", country: "Denmark", decimals: 2 },
  { code: "CZK", symbol: "K\u010D", name: "Czech Koruna", country: "Czech Republic", decimals: 2 },
  { code: "HUF", symbol: "Ft", name: "Hungarian Forint", country: "Hungary", decimals: 0 },
  { code: "THB", symbol: "\u0E3F", name: "Thai Baht", country: "Thailand", decimals: 2 },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar", country: "Singapore", decimals: 2 },
  { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar", country: "Hong Kong", decimals: 2 },
  { code: "TWD", symbol: "NT$", name: "Taiwan Dollar", country: "Taiwan", decimals: 0 },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit", country: "Malaysia", decimals: 2 },
  { code: "PHP", symbol: "\u20B1", name: "Philippine Peso", country: "Philippines", decimals: 2 },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah", country: "Indonesia", decimals: 0 },
  { code: "VND", symbol: "\u20AB", name: "Vietnamese Dong", country: "Vietnam", decimals: 0 },
  { code: "AED", symbol: "AED", name: "UAE Dirham", country: "United Arab Emirates", decimals: 2 },
  { code: "SAR", symbol: "SAR", name: "Saudi Riyal", country: "Saudi Arabia", decimals: 2 },
  { code: "EGP", symbol: "E\u00A3", name: "Egyptian Pound", country: "Egypt", decimals: 2 },
  { code: "NGN", symbol: "\u20A6", name: "Nigerian Naira", country: "Nigeria", decimals: 2 },
  { code: "ARS", symbol: "AR$", name: "Argentine Peso", country: "Argentina", decimals: 2 },
  { code: "CLP", symbol: "CL$", name: "Chilean Peso", country: "Chile", decimals: 0 },
  { code: "COP", symbol: "COL$", name: "Colombian Peso", country: "Colombia", decimals: 0 },
  { code: "PEN", symbol: "S/.", name: "Peruvian Sol", country: "Peru", decimals: 2 },
];
